Before running code, type into terminal:
    
    py -3.12.4 -m venv my_venv
^this creates the virtual enviornment with Python 3.12

    venv\Scripts\activate
^this activates the virtual environment

    python -m pip install -r requirements.txt
^this installs packages according to the requirements.txt file

In [8]:
#Importing phydrus
import os

from EditedFunctions_260226_mr import Model #Meghan's edits for roots
import ProfileFunction as pl #Profile function from GitHub
import PlottingFunctions as Plots #Plotting function from GitHub
import run_hydrus as rh

import datetime
from pathlib import Path
from typing import Union, Optional
import copy
import numpy as np
np.random.seed(42)
from matplotlib import axes
import xarray as xr
import pandas as pd
from spotpy.algorithms import _algorithm
import spotpy
import tqdm
from scipy.stats import wasserstein_distance
import dask.array as da
import matplotlib.pyplot as plt 
import time

import multiprocessing as mp
mp.set_start_method("spawn", force=True)

In [2]:
#Doing working directory stuff

#set working directory manually (I'm sure there is a better way to do this)
#os.chdir('C:\\Users\\meghanrobinson\\Downloads\\Modeling\\PHydrusTest\\PipelineStructure')

#give path to exe file
exe = os.path.join(os.getcwd(), "H1D_Dual.exe")

#name the folder files will fill
main_level = os.path.normpath(os.path.join(os.getcwd(), os.pardir))
newfolder = str(datetime.date.today())
ws = os.path.join(main_level, '3_Results', newfolder)

## Define Multidimensional Objective Functions

In [3]:
obj_func_direction = {
    'mse': 'minimize',
    'rmse': 'minimize',
    'nrmse': 'minimize',
    'nse': 'maximize',
    'pbias': 'minimize',
    'rmse_eta': 'minimize',
    'rmse_swe': 'minimize',
}

def mse_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    if observation.shape[axis] == simulation.shape[axis]:
        mse = np.nanmean((observation - simulation) ** 2, axis=axis)
        if return_dict:
            return {'mse': mse}
        else:
            return mse
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")


def rmse_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    print("simulation.shape:", simulation.shape)
    print("observation.shape:", observation.shape)
    if observation.shape[axis] == simulation.shape[axis]:
        mse = mse_md(observation, simulation, axis=axis)
        rmse = np.sqrt(mse)
        if return_dict:
            return {'rmse': rmse}
        else:
            return rmse
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")


def nrmse_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    if observation.shape[axis] == simulation.shape[axis]:
        nrmse = rmse_md(observation, simulation, axis=axis) / np.nanmean(observation, axis=axis)
        if return_dict:
            return {'nrmse': nrmse}
        else:
            return nrmse
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")


def nse_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    if observation.shape[axis] == simulation.shape[axis]:
        mean_observed = np.nanmean(observation, axis=axis)
        # compute numerator and denominator
        numerator = np.nansum((observation - simulation) ** 2, axis=axis)
        denominator = np.nansum((observation - mean_observed) ** 2, axis=axis)
        # compute coefficient
        nse = 1 - (numerator / denominator)
        if return_dict:
            return {'nse': nse}
        else:
            return nse
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")


def pbias_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    if observation.shape[axis] == simulation.shape[axis]:
        pbias = np.nansum(simulation - observation, axis=axis) / np.nansum(observation, axis=axis)
        if return_dict:
            return {'pbias': pbias}
        else:
            return pbias
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")
    

# # These two functions didn't work because they were introducing a new dimension.
# def rmse_eta_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
#     # # For SA
#     # observation = observation[0]
#     # simulation = simulation[0]

#     # For Calibration
#     observation = observation[:, 0]
#     simulation = simulation[:, 0]
#     if observation.shape[axis] == simulation.shape[axis]:
#         mse = mse_md(observation, simulation, axis=axis)
#         rmse = np.sqrt(mse)
#         if return_dict:
#             return {'rmse_eta': rmse}
#         else:
#             return rmse
#     else:
#         raise ValueError("evaluation and simulation data do not have the same length.")
    
# def rmse_swe_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
#     # # For SA
#     # observation = observation[1]
#     # simulation = simulation[1]

#     # For Calibration
#     observation = observation[:, 1]
#     simulation = simulation[:, 1]
#     if observation.shape[axis] == simulation.shape[axis]:
#         mse = mse_md(observation, simulation, axis=axis)
#         rmse = np.sqrt(mse)
#         if return_dict:
#             return {'rmse_swe': rmse}
#         else:
#             return rmse
#     else:
#         raise ValueError("evaluation and simulation data do not have the same length.")
    
def rmse_eta_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    
    # Controlling different dimensions
    if len(observation.shape) == 2:
        # For SA
        observation = observation[:len(observation)//2]
        simulation = simulation[:len(simulation)//2]
    else:
        # For Calibration
        observation = observation[:, :len(observation[0])//2]
        simulation = simulation[:, :len(simulation[0])//2]

    # Actually running the analysis
    if observation.shape[axis] == simulation.shape[axis]:
        mse = mse_md(observation, simulation, axis=axis)
        rmse = np.sqrt(mse)
        if return_dict:
            return {'rmse_eta': rmse}
        else:
            return rmse
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")
    
def rmse_swe_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    
    # Controlling different dimensions
    if len(observation.shape) == 2:
        # For SA
        observation = observation[len(observation)//2:]
        simulation = simulation[len(simulation)//2:]
    else:
        # For Calibration
        observation = observation[:, len(observation[0])//2:]
        simulation = simulation[:, len(simulation[0])//2:]

    # Actually running the analysis
    if observation.shape[axis] == simulation.shape[axis]:
        mse = mse_md(observation, simulation, axis=axis)
        rmse = np.sqrt(mse)
        if return_dict:
            return {'rmse_swe': rmse}
        else:
            return rmse
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")

## Classes for MSC-UA Calibration

In [4]:
# Base class for a multidimensional database for the calibration. This could be used in future expansion to other formats
class MultiDimDb:
    format = None
    def __init__(
            self,
            dbname: str,
            dbpath: Union[str, Path],
            dims: Optional[dict] = None,
            dim_names: Optional[dict] = None,
            dbappend: bool = False,
            save_sim: bool = False,
    ):
        
        self.dbname = dbname
        self.cwd = dbpath
        self.dims = dims
        self.dim_names = dim_names
        self.dbappend = dbappend
        self.save_sim = save_sim

        self.ppu_upper = None
        self.ppu_lower = None
        self.pfactor = None
        self.rfactor = None
        self.thresholds = None
        self.best_sim = None
        self.best_params = None
        self.best_objfun = None


class MscuaSetup:
    # Define parameters here (before __init__) as variables

    def __init__(self, objective_funcs, type='run_interation', dbase: Optional[Union[str, Path, MultiDimDb]] = None):
        self.setup_type = type
        self.parameter_dimension = {}
        self.param_dim_names = {}
        self.indata = None
        self.observation_data = None
        if isinstance(objective_funcs, list):
            self.objfuncs = objective_funcs
        else:
            self.objfuncs = [objective_funcs]

    def parameters(self):
        pass
    
    def simulation(self):
        pass

    def evaluation(self):
        pass

    def objectivefunction(self, observation, simulation):
        pass


# accepts 2 types of setup classes, a MscuaSetup() object with attribute .setup_type = 'run_iteration' OR .setup_type = 'evaluate_iteration'
# Can use custom objective functions for filtering parameter sets but note that they must return a dictionary {'name_of_function': np.ndarray(values)}
class MsCua:
    
    algorithm_name = "MSCUA"
    
    def __init__(
            self,
            setup_class: MscuaSetup,
            dbname: str = 'mscuaDb',
            dbformat: str = 'memory',
            dbappend: bool = False,
            iter_db: Union[str, Path, None] = None

    ):
        self.setup = setup_class
        if dbformat == 'memory':
            self.database = MemDb(dbname=dbname)
        else:
            raise NotImplementedError("Other databases not supported yet, choose 'memory'")
        
        self.observation_data = self.setup.evaluation()

    def evaluate_iteration(self, dbase: MultiDimDb, objfunc_thresh: dict, min_pfactor: float = 0.35, min_refparams: int = 25):
        """
        Example objfunc_thresh dict:
        {'nse': 0.5, 'nrmse': 0.1}
            
        """
        if dbase.format == 'memory':
            if not dbase.parameter_samples:
                raise AttributeError("No paramter samples have been saved to the input database.")
            if len(dbase.simulation_results) == 0:
                raise AttributeError("No simulation data has been saved to the input database.")
            
            dbase.thresholds = objfunc_thresh
            dbase.thresholds.update({"pfactor_threshold": min_pfactor})
            dbase.thresholds.update({"min_refined_params_threshold": min_refparams})
            dbase._ref_par = copy.deepcopy(dbase._par_samples)
            reps = len(dbase.simulation_results)
            print("Evaluating Objective Function Values...")
            # need to convert simulation_results into an array here...sooner than it was
            sims_arr = np.array(dbase.simulation_results)
            ob = self.setup.objectivefunction(self.observation_data[None,:,:], sims_arr)
            if not isinstance(ob, dict):
                raise ValueError("The setup class's objective function method did not return a dictionary. " \
                "A dictionary of objective functions is required.")
            dbase.save(objective_func=ob)
            best_sim = {}
            best_obfn = {}
            best_params = {}
            for k,v in ob.items():
                if obj_func_direction[k] == 'minimize':
                    # print()
                    # print('array: ', sims_arr.shape)
                    # print(f'k: {k}, v: {v.shape}')
                    # print(f'{v.argmin(axis=0).shape}, :, {v.shape[1]}')
                    best_rep = sims_arr[v.argmin(axis=0),:,np.arange(v.shape[1])].T
                    best_ob = v[v.argmin(axis=0),np.arange(v.shape[1])]
                    best_par = {}
                    for pk,pv in dbase.refined_parameters.items():
                        best_par.update({pk: pv[v.argmin(axis=0), np.arange(v.shape[1])]})
                    
                    # print()
                    # print('array: ', sims_arr.shape)
                    # print(f'k: {k}, v: {v.shape}')
                    # print(f'{v.argmin(axis=1).shape}, :, {v.shape[2]}')
                    # best_rep = sims_arr[v.argmin(axis=1),:,np.arange(v.shape[2])].T
                    # best_ob = v[v.argmin(axis=1),np.arange(v.shape[2])]
                    # best_par = {}
                    # for pk,pv in dbase.refined_parameters.items():
                    #     best_par.update({pk: pv[v.argmin(axis=0), np.arange(v.shape[1])]})
                elif obj_func_direction[k] == 'maximize':
                    best_rep = sims_arr[v.argmax(axis=0),:,np.arange(v.shape[1])].T
                    best_ob = v[v.argmax(axis=0),np.arange(v.shape[1])]
                    best_par = {}
                    for pk,pv in dbase.refined_parameters.items():
                        best_par.update({pk: pv[v.argmax(axis=0), np.arange(v.shape[1])]})
                else:
                    raise ValueError("The objective function threshold direction is not recognized.")
                best_sim.update({k: best_rep})
                best_obfn.update({k: best_ob})
                best_params.update({k: best_par})
            dbase.best_sim = best_sim
            dbase.best_params = best_params
            dbase.best_objfun = best_obfn
            fil = {}
            for k,v in ob.items():
                if k not in list(objfunc_thresh.keys()):
                    raise ValueError(f"No threshold was provided for objective function {k}.")
                if obj_func_direction[k] == 'minimize':
                    filter = np.where(v > objfunc_thresh[k])
                elif obj_func_direction[k] == 'maximize':
                    filter = np.where(v < objfunc_thresh[k])
                else:
                    raise ValueError("The objective function threshold direction is not recognized.")
                fil[k] = filter
                for park in dbase.refined_parameters.keys():
                    for k, v in fil.items():
                        dbase._ref_par[park][v] = np.nan
            param_nans = np.isnan(dbase.refined_parameters[list(dbase.refined_parameters.keys())[0]])
            refined_param_cnt = np.count_nonzero(~param_nans, axis=0)
            print(f"Max number of refined parameter sets: {refined_param_cnt.max()}")
            print(f"Min number of refined parameter sets: {refined_param_cnt.min()}")
            ref_less_than = np.count_nonzero(refined_param_cnt < min_refparams)
            # Remove simulations from sim_arr that did not meet objective function thresholds
            ref_sims_idx = np.where(param_nans)
            sims_arr[ref_sims_idx[0],:,ref_sims_idx[1]] = np.nan
            ## calculate 95PPU here
            print("Calculating the 95PPU...")
            obs_sd = np.std(self.observation_data, axis=0)
            up95ppu = np.nanquantile(sims_arr, 0.975, axis=0)
            lo95ppu = np.nanquantile(sims_arr, 0.025, axis=0)
            print("Calculating p- and r-factor metrics...")
            pfac_arr = np.where((self.observation_data <= up95ppu) & (self.observation_data >= lo95ppu), 1, 0)
            pfac_cnt = np.count_nonzero(pfac_arr, axis=0)
            pfactor = pfac_cnt / up95ppu.shape[0]
            ppu_diff = (up95ppu - lo95ppu).mean(axis=0)
            rfactor = ppu_diff / obs_sd
            print(f"Max p-factor = {pfactor.max()}")
            print(f"Min p-factor = {pfactor.min()}")
            print(f"Min r-factor = {np.nanmin(rfactor)}")
            print(f"Max r-factor = {np.nanmax(rfactor)}")
            dbase.ppu_upper = up95ppu
            dbase.ppu_lower = lo95ppu
            dbase.pfactor = pfactor
            dbase.rfactor = rfactor

            if ref_less_than == 0:
                print(f"All models retained more refined parameter sets than the minimun: {min_refparams}.")
                if np.count_nonzero(pfactor < min_pfactor) == 0:
                    print(f"All models had p-factor greater than {min_pfactor}")
                else:
                    print(f"{np.count_nonzero(pfactor < min_pfactor)} models had a p-factor lower than the allowable minimum: {min_pfactor}. Returning array of failed indexes.")
                    return np.where(pfactor < min_pfactor)[0]
            else:
                print(f"{ref_less_than} models had fewer than the minimum allowable refined parameter sets: {min_refparams}. Either increase the number of samples or exclude these models.")
                print(f"Returning array of failed model indexes.")
                if np.count_nonzero(pfactor < min_pfactor) == 0:
                    print(f"All models had p-factor greater than {min_pfactor}")
                    return np.where(refined_param_cnt < min_refparams)[0]
                else:
                    print(f"{np.count_nonzero(pfactor < min_pfactor)} models had a p-factor lower than the allowable minimum: {min_pfactor}. Returning array of failed indexes.")
                    return np.where(pfactor < min_pfactor)[0], np.where(refined_param_cnt < min_refparams)[0]        

        else:
            raise NotImplementedError("Other databases not supported")

    def sample(self, reps: int, objfunc_thresholds: dict, min_pfactor: float = 0.35, min_refparams: int = 25, **kwargs):
        plist = build_parameter_list(self.setup, self.setup.parameter_dimension, self.setup.param_dim_names)
        samples, newdb = LHS_md(plist, repetitions=reps, dbase=self.database, **kwargs)
        self.database = newdb
        run_multidim_model_reps(self.setup, self.database)
        iter_result = self.evaluate_iteration(self.database, objfunc_thresholds, min_pfactor, min_refparams)
        if iter_result is None:
            return None
        else:
            return iter_result

    def _evaluate_rep(self, obs_data: np.ndarray, rep_simulations: np.ndarray, objfunc_thresh: dict):
        ob = self.setup.objectivefunction(obs_data, rep_simulations)
        if not isinstance(ob, dict):
            raise ValueError("The setup class's objective function method did not return a dictionary. A dictionary of objective functions is required.")
        fil = {}
        for k,v in ob.items():
            if k not in list(objfunc_thresh.keys()):
                raise ValueError(f"No threshold was provided for objective function {k}.")
            if obj_func_direction[k] == 'minimize':
                filter = np.where(v > objfunc_thresh[k])
            elif obj_func_direction[k] == 'maximize':
                filter = np.where(v < objfunc_thresh[k])
            else:
                raise ValueError("The objective function threshold direction is not recognized.")
            
            fil[k] = filter
        
        return ob, fil


class MsCuaAnalyzer:

    def __init__(self, dbase: Union[MultiDimDb, xr.Dataset]):
        
        if isinstance(dbase, MultiDimDb):
            self.dbase = dbase
            if self.dbase.format == 'memory':
                self.ds = self.dbase.to_xarray()
            else:
                self.ds = self.dbase
        else:
            self.dbase = None
            self.ds = dbase

    def plot_pfactor(self, threshold: bool = False):
        ax = plt.axes()
        ax.hist(self.ds.pfactor.values)
        if threshold:
            ax.axvline(self.ds.pfactor_threshold.values, color='black', ls='--', label='Threshold')
            ax.legend()
        ax.set_ylabel("Frequency", fontsize=12)
        ax.set_xlabel("pfactor Value", fontsize=12)
        plt.show()
    
    def plot_rfactor(self):
        ax = plt.axes()
        ax.hist(self.ds.rfactor.values)
        ax.set_ylabel("Frequency", fontsize=12)
        ax.set_xlabel("rfactor Value", fontsize=12)
        plt.show()
    
    def plot_refined_parameters(self, param: str, indx: int = 0, ax: Optional[axes.Axes] = None, **kwargs):
        if ax is None:
            ax = plt.axes()
        else:
            ax = ax
        ax.hist(self.ds[f"{param}_refined"].values[:,indx])
        ax.set_ylabel("Frequency", fontsize=12)
        ax.set_xlabel(f"Refined {param} Value", fontsize=12)
        plt.show()
    
    def compare_parameter_distributions(self, param: str, comp_dstb: Union[np.ndarray, list], indx: int = 0, ax: Optional[axes.Axes] = None, **kwargs):
        dims = self.ds[f"{param}_samples"].dims
        if ax is None:
            ax = plt.axes()
        else:
            ax = ax
        ax.hist(comp_dstb, label='comparison parameter values', **kwargs)
        ax.hist(self.ds[f"{param}_refined"].values[:,indx], label='refined parameter values', **kwargs)
        ax.set_ylabel("Frequency", fontsize=12)
        ax.set_xlabel(f"{param} Value", fontsize=12)
        ax.set_title(f"{dims[1]}: {indx}", fontsize=12)
        ax.legend()
        plt.show()
    
    def plot_ppu(self, indx: int = 0, best_sim: bool = False, obs_data: Optional[np.ndarray] = None, sort: bool = False, ax: Optional[axes.Axes] = None):
        dims = self.ds["95PPU_lower"].dims
        if ax is None:
            ax = plt.axes()
        else:
            ax = ax
        if sort:
            srt_idx = np.argsort(self.ds["95PPU_lower"].values[:,indx])
            ax.fill_between(np.arange(self.ds["95PPU_lower"].values.shape[0]), 
                            self.ds["95PPU_upper"].values[srt_idx,indx], 
                            self.ds["95PPU_lower"].values[srt_idx,indx], 
                            label="95 Percentile Prediction Uncertainty",
                            ec='blue',
                            alpha=0.3)
            if obs_data is not None:
                if self.ds["95PPU_lower"].values.shape != obs_data.shape:
                    raise ValueError("The input observation data does not match the size of the modeled 95 percent prediction uncertainty.")
                ax.plot(np.sort(obs_data[:,indx]), marker=None, ls='-', lw=1.2, color='black', label='Observed Values')
            if best_sim:
                for i in self.ds["objective_functions"].values:
                    ax.plot(self.ds[f"best_simulation_{i}"].values[srt_idx, indx], marker=None, ls='--', lw=1, color='red', label=f'Best Model Simulation - {i}')
        else:
            ax.fill_between(np.arange(self.ds["95PPU_lower"].values.shape[0]), 
                            self.ds["95PPU_upper"].values[:,indx], 
                            self.ds["95PPU_lower"].values[:,indx], 
                            label="95 Percentile Prediction Uncertainty")
            if obs_data is not None:
                if self.ds["95PPU_lower"].values.shape != obs_data.shape:
                    raise ValueError("The input observation data does not match the size of the modeled 95 percent prediction uncertainty.")
                ax.plot(obs_data[:,indx], marker=None, ls='-', lw=1.25, color='black', label='Observed Values')
            if best_sim:
                for i in self.ds["objective_functions"].values:
                    ax.plot(self.ds[f"best_simulation_{i}"].values[:, indx], marker=None, ls='--', lw=1, color='red', label=f'Best Model Simulation - {i}')
        ax.set_ylabel("Model Output Values", fontsize=12)
        ax.set_xlabel(dims[0], fontsize=12)
        ax.set_title(f"{dims[1]}: {indx}", fontsize=12)
        ax.legend()
        ax.set_yscale('log')
        plt.show()

    def plot_objective_functions(self, indx: int = 0, threshold: bool = False):
        n = len(self.ds.objective_functions)
        if n % 2 == 0:
            # fig, axs = plt.subplots(int(n/2), 2, sharex=True)
            fig, axs = plt.subplots(int(n/2), 2, sharex=False)
        else:
            # fig, axs = plt.subplots(int(n/2+1), 2, sharex=True)
            fig, axs = plt.subplots(int(n/2+1), 2, sharex=False)
        for i, v in enumerate(self.ds.objective_functions.values.tolist()):
            if i % 2 == 0:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 0]
                else:
                    ax_i = axs[0]
                ax_i.hist(self.ds[v].values[:, indx])
                if threshold:
                    thresh = self.ds.obj_func_thresholds.sel(objective_functions=v).values
                    ax_i.axvline(thresh, color='black', ls='--', label='Threshold')
                    ax_i.legend()
                ax_i.set_title(f"{self.ds[v].dims[1]} {indx}: {v}")
            else:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 1]
                else:
                    ax_i = axs[1]
                ax_i.hist(self.ds[v].values[:, indx])
                if threshold:
                    thresh = self.ds.obj_func_thresholds.sel(objective_functions=v).values
                    ax_i.axvline(thresh, color='black', ls='--', label='Threshold')
                    ax_i.legend()
                ax_i.set_title(f"{self.ds[v].dims[1]} {indx}: {v}")
        if n % 2 != 0:
            if len(axs.shape) > 1:
                for l in axs[int(n/2)-1,1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[int(n/2), 1])
                for ax in axs[-1, :]:
                    ax.set_xlabel('Objective Function Value')
                for ax in axs[:, 0]:
                    ax.set_ylabel('Frequency')
            else:
                for l in axs[1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[1])
                for ax in axs:
                    ax.set_xlabel('Objective Function Value')
                axs[0].set_ylabel('Frequency')
        plt.tight_layout()
        plt.show()

    def plot_best_objfuncs(self, threshold: bool = False):
        n = len(self.ds.objective_functions)
        if n % 2 == 0:
            # fig, axs = plt.subplots(int(n/2), 2, sharex=True)
            fig, axs = plt.subplots(int(n/2), 2, sharex=False)
        else:
            # fig, axs = plt.subplots(int(n/2+1), 2, sharex=True)
            fig, axs = plt.subplots(int(n/2+1), 2, sharex=False)
        for i, v in enumerate(self.ds.objective_functions.values.tolist()):
            if i % 2 == 0:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 0]
                else:
                    ax_i = axs[0]
                ax_i.hist(self.ds.best_obj_function.sel(objective_functions=v).values)
                if threshold:
                    thresh = self.ds.obj_func_thresholds.sel(objective_functions=v).values
                    ax_i.axvline(thresh, color='black', ls='--', label='Threshold')
                    ax_i.legend()
                ax_i.set_title(f"Best {v} value per {self.ds[v].dims[1]}")
            else:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 1]
                else:
                    ax_i = axs[1]
                ax_i.hist(self.ds.best_obj_function.sel(objective_functions=v).values)
                if threshold:
                    thresh = self.ds.obj_func_thresholds.sel(objective_functions=v).values
                    ax_i.axvline(thresh, color='black', ls='--', label='Threshold')
                    ax_i.legend()
                ax_i.set_title(f"Best {v} value per {self.ds[v].dims[1]}")
        if n % 2 != 0:
            if len(axs.shape) > 1:
                for l in axs[int(n/2)-1,1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[int(n/2), 1])
                for ax in axs[-1, :]:
                    ax.set_xlabel('Objective Function Value')
                for ax in axs[:, 0]:
                    ax.set_ylabel('Frequency')
            else:
                for l in axs[1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[1])
                for ax in axs:
                    ax.set_xlabel('Objective Function Value')
                axs[0].set_ylabel('Frequency')
        plt.tight_layout()
        plt.show()
    
    def plot_number_refined_params(self, threshold: bool = False):
        arb_parm = self.ds.parameters.values[0]
        nans = np.isnan(self.ds[f"{arb_parm}_refined"].values)
        nz = np.count_nonzero(~nans, axis=0)
        ax = plt.axes()
        ax.hist(nz)
        if threshold:
            ax.axvline(self.ds.min_refined_params_threshold.values, color='black', ls='--', label='Threshold')
            ax.legend()
        ax.set_ylabel("Frequency", fontsize=12)
        ax.set_xlabel("Number Refined Parameter Sets", fontsize=12)
        plt.show()
    
    def calc_param_distribution_change(self, param: str, comp_dstb: Union[np.ndarray, list], indx: int = 0):
        d1 = comp_dstb
        d2 = self.ds[f"{param}_refined"].values[:,indx]
        ws_dist = wasserstein_distance(d1[~np.isnan(d1)], d2[~np.isnan(d2)])

        return ws_dist


class SensitivityAnalysis:

    def __init__(self,
                 setup_class: MscuaSetup,
                 ):
        
        self.setup = setup_class
                
        self.observation_data = self.setup.evaluation()
        self.results = None

    def sample(self, reps: int = 10):
        plist = build_parameter_list(self.setup, self.setup.parameter_dimension, self.setup.param_dim_names)
        pnames = []
        objf_names = None
        init_samp = {}
        for p in plist:
            name = p.name
            pnames.append(name)
            sv = np.repeat(p(), p.dim)
            init_samp.update({name: sv})
        rslt = xr.Dataset()
        rslt.coords['parameters'] = (('parameters',), pnames)
        rslt.coords['repetitions'] = (('repetitions',), np.arange(reps)+1)
        rslt.coords[plist[0].dim_name] = ((plist[0].dim_name,), np.arange(plist[0].dim)+1)
        arr_sz = (len(pnames), reps, self.setup.parameter_dimension[pnames[0]])
        active_samp = copy.deepcopy(init_samp)
        segment = 1 / float(reps)
        rslt['samples'] = (('parameters', 'repetitions', plist[0].dim_name), da.from_array(np.empty(arr_sz), chunks='auto'))
        for i, p in enumerate(plist):
            # sample parameter space here
            parmin = p.minbound
            parmax = p.maxbound
            
            if isinstance(parmin, float):
                parmin = np.repeat(parmin, p.dim)
            if isinstance(parmax, float):
                parmax = np.repeat(parmax, p.dim)
                
            print(f"Sampling {reps} repetitions of the {p.name} parameter...")
            for r in tqdm.tqdm(range(reps), desc=f"{p.name} samples", leave=False):
                # iterate samples per paramter here, run simulation, calculate objective function and assign values
                segmentMin = r * segment
                pointInSegment = segmentMin + (np.random.random() * segment)
                parset = pointInSegment * (parmax - parmin) + parmin
                active_samp[p.name] = parset
                rslt['samples'].values[i, r, :] = parset
                sim = self.setup.simulation(active_samp)
                ob = self.setup.objectivefunction(self.observation_data, sim)
                if objf_names is None:
                    objf_names = []
                    for k in ob.keys():
                        objf_names.append(k)
                    rslt.coords['objective_functions'] = (('objective_functions',), objf_names)
                # logic to check for obj func name in dataset datavars, if not there, add (initialize dask empty dask array), if it is there append by index
                for k,v in ob.items():
                    if k not in list(rslt.data_vars):
                        rslt[k] = (('parameters', 'repetitions', p.dim_name), da.from_array(np.empty(arr_sz), chunks='auto'))
                        rslt[k].values[i,r,:] = v
                    else:
                        rslt[k].values[i,r,:] = v
            # result active samp
            active_samp[p.name] = init_samp[p.name]
        
        sens_indx = da.from_array(np.empty((len(rslt['objective_functions'].values), arr_sz[0], arr_sz[2])), chunks='auto')
        for i, obf in enumerate(rslt['objective_functions'].values.tolist()):
            d = np.nanmax(rslt[obf].values, axis=(0,1)) - np.nanmin(rslt[obf].values, axis=(0,1))
            for j, par in enumerate(rslt['parameters'].values.tolist()):
                n = np.nanmax(rslt[obf].sel(parameters=par).values, axis=0) - np.nanmin(rslt[obf].sel(parameters=par).values, axis=0)
                sens_arr = n / d
                sens_indx[i, j, :] = sens_arr
        rslt['sensitivity_index'] = (('objective_functions', 'parameters', plist[0].dim_name), sens_indx)
        self.results = rslt

    def plot_sensitivity_index(self, indx: int = 0):
        if self.results is None:
            raise AttributeError("The sensitivity analysis has not been run yet, the results are empty.")
        
        n = len(self.results.objective_functions)
        if n % 2 == 0:
            fig, axs = plt.subplots(int(n/2), 2)
        else:
            fig, axs = plt.subplots(int(n/2+1), 2)
        for i, v in enumerate(self.results.objective_functions.values.tolist()):
            if i % 2 == 0:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 0]
                else:
                    ax_i = axs[0]
                ax_i.bar(self.results.parameters.values, self.results['sensitivity_index'].sel(objective_functions=v).values[:,indx])
                ax_i.set_title(f"{v}: {self.results['sensitivity_index'].dims[2]} {indx}")
            else:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 1]
                else:
                    ax_i = axs[1]
                ax_i.bar(self.results.parameters.values, self.results['sensitivity_index'].sel(objective_functions=v).values[:,indx])
                ax_i.set_title(f"{v}: {self.results['sensitivity_index'].dims[2]} {indx}")
        if n % 2 != 0:
            if len(axs.shape) > 1:
                for l in axs[int(n/2)-1,1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[int(n/2), 1])
                for ax in axs[:, 0]:
                    ax.set_ylabel('Sensitivity Index')
            else:
                for l in axs[1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[1])
                axs[0].set_ylabel('Sensitivity Index')
        plt.tight_layout()
        plt.show()

    def plot_sensitivity_distribution(self, param: str):
        if self.results is None:
            raise AttributeError("The sensitivity analysis has not been run yet, the results are empty.")
        
        n = len(self.results.objective_functions)
        if n % 2 == 0:
            fig, axs = plt.subplots(int(n/2), 2)
        else:
            fig, axs = plt.subplots(int(n/2+1), 2)
        for i, v in enumerate(self.results.objective_functions.values.tolist()):
            if i % 2 == 0:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 0]
                else:
                    ax_i = axs[0]
                ax_i.hist(self.results['sensitivity_index'].sel(objective_functions=v, parameters=param).values)
                ax_i.set_xlabel(f"{param} Sensitivity Indexes")
                ax_i.set_ylabel("Frequency")
                ax_i.set_title(f"{v}")
            else:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 1]
                else:
                    ax_i = axs[1]
                ax_i.hist(self.results['sensitivity_index'].sel(objective_functions=v, parameters=param).values)
                ax_i.set_xlabel(f"{param} Sensitivity Indexes")
                ax_i.set_ylabel("Frequency")
                ax_i.set_title(f"{v}")
        if n % 2 != 0:
            if len(axs.shape) > 1:
                for l in axs[int(n/2)-1,1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[int(n/2), 1])
            else:
                for l in axs[1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[1])
        plt.tight_layout()
        plt.show()
    
    def plot_obj_func(self, obj_func: str, indx: int = 0):
        if self.results is None:
            raise AttributeError("The sensitivity analysis has not been run yet, the results are empty.")
        
        n = len(self.results.parameters)
        if n % 2 == 0:
            fig, axs = plt.subplots(int(n/2), 2)
        else:
            fig, axs = plt.subplots(int(n/2+1), 2)
        for i, v in enumerate(self.results.parameters.values.tolist()):
            if i % 2 == 0:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 0]
                else:
                    ax_i = axs[0]
                ax_i.plot(self.results['samples'].sel(parameters=v).values[:,indx], self.results[obj_func].sel(parameters=v).values[:,indx])
                ax_i.set_xlabel(f"{v} Value")
                ax_i.set_ylabel(obj_func)
            else:
                if len(axs.shape) > 1:
                    ax_i = axs[int(i/2), 1]
                else:
                    ax_i = axs[1]
                ax_i.plot(self.results['samples'].sel(parameters=v).values[:,indx], self.results[obj_func].sel(parameters=v).values[:,indx])
                ax_i.set_xlabel(f"{v} Value")
                ax_i.set_ylabel(obj_func)
        if n % 2 != 0:
            if len(axs.shape) > 1:
                for l in axs[int(n/2)-1,1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[int(n/2), 1])
            else:
                for l in axs[1].get_xaxis().get_majorticklabels():
                    l.set_visible(True)
                fig.delaxes(axs[1])
        plt.tight_layout()
        plt.show()
    

# A child class of MultiDimDb that creates a set of zarr files to database calibration output
class ZarrDb(MultiDimDb):
    format = 'zarr'
    def __init__(self, *args, chunks: Optional[dict] = None, **kwargs):
        
        super(ZarrDb, self).__init__(*args, **kwargs)
        self.chunks = chunks
    
    def save(self):
        pass

    @staticmethod
    def load(dbpth: Union[str, Path]):
        pass


# create a netcdf with dummy data and then write to each region to fill it out...use chunks for dask capabilities?
class NetcdfDb(MultiDimDb):
    format = 'netcdf'
    def __init__(self, *args, chunks: Optional[dict] = None, **kwargs):
        
        super(NetcdfDb, self).__init__(*args, **kwargs)
        self.chunks = chunks
    
    def save(self):
        pass

    @staticmethod
    def load(dbpth: Union[str, Path]):
        pass


class MemDb(MultiDimDb):
    format = 'memory'

    def __init__(self, *args, **kwargs):
        
        super(MemDb, self).__init__(*args, dbpath=None, **kwargs)
        print("In Memory database initialized...")
        self._par_samples = {}
        self._ref_par = {}
        self._objfun = {}
        self._sim = []
        self._obs_index = None
    
    @property
    def simulation_results(self):
        return np.array(self._sim)
    
    @property
    def parameter_samples(self):
        return self._par_samples
    
    @property
    def refined_parameters(self):
        return self._ref_par

    @property
    def objective_func_values(self):
        return self._objfun

    @property
    def observation_labels(self):
        return self._obs_index
    
    @observation_labels.setter
    def observation_labels(self, new_in: np.ndarray):
        if self.simulation_results is None:
            raise AttributeError("No simulation results, save simulations first before assigning observation labels.")
        if new_in.size != self.simulation_results[0].shape[1]:
            raise ValueError("The input array is not the same length as observations dimension.")
        self._obs_index = new_in

    def save(self, param_dict: Optional[dict] = None, objective_func: Optional[dict] = None, simulations: Optional[np.ndarray] = None):
        if (param_dict is None) & (objective_func is None) & (simulations is None):
            print("No data to save")
        else:
            if param_dict is not None:
                if not self._par_samples:
                    self._par_samples.update(param_dict)
                else:
                    for k,v in param_dict.items():
                        self._par_samples[k] = np.vstack((self._par_samples[k], v))
            
            if objective_func is not None:
                if not self._objfun:
                    self._objfun.update(objective_func)
                else:
                    for k,v in objective_func.items():
                        self._objfun[k] = np.vstack((self._objfun[k], v))
            
            if simulations is not None:
                self._sim.append(simulations)

    def to_xarray(self):
        ds = xr.Dataset()
        param_names = []
        for k in list(self._par_samples.keys()):
            param_names.append(k)
        objfunc_names = []
        for k in list(self.objective_func_values):
            objfunc_names.append(k)
        if self.parameter_samples is not None:
            for pnm in param_names:
                ds[f"{pnm}_samples"] = (("repetition", self.dim_names[pnm]), self.parameter_samples[pnm], {"description": "original parameter sample"})
        if self.refined_parameters is not None:
            for pnm in param_names:
                ds[f"{pnm}_refined"] = (("repetition", self.dim_names[pnm]), self.refined_parameters[pnm], {"description": "refined parameter set"})
        if self.objective_func_values is not None:
            for obf in objfunc_names:
                ds[obf] = (("repetition", self.dim_names[list(self.dim_names.keys())[0]]), self.objective_func_values[obf], {"description": "objective function"})
                if self.best_sim is not None:
                    ds[f"best_simulation_{obf}"] = (("observation", self.dim_names[list(self.dim_names.keys())[0]]), self.best_sim[obf], {"description": f"the simulation repetition with the best {obf} value"})
                
            if self.best_objfun is not None:
                bst_obfn = []
                bst_params = []
                for obf in objfunc_names:
                    bst_obfn.append(self.best_objfun[obf])
                    bst_p_mid = []
                    if self.best_params is not None:
                        for pnm in param_names:
                            bst_p_mid.append(self.best_params[obf][pnm])
                        bst_p_arr = np.array(bst_p_mid)
                        bst_params.append(bst_p_arr)
                ds["best_obj_function"] = (("objective_functions", self.dim_names[list(self.dim_names.keys())[0]]), np.array(bst_obfn))
                if self.best_params is not None:
                    ds["best_parameter_set"] = (("objective_functions", "parameters", self.dim_names[list(self.dim_names.keys())[0]]), np.array(bst_params))
        
        if len(self.simulation_results) != 0:
            ds["simulation_results"] = (("repetition", "observation", self.dim_names[list(self.dim_names.keys())[0]]), np.array(self._sim))
        if self.pfactor is not None:
            ds["pfactor"] = ((self.dim_names[list(self.dim_names.keys())[0]]), self.pfactor)
        if self.rfactor is not None:
            ds["rfactor"] = ((self.dim_names[list(self.dim_names.keys())[0]]), self.rfactor)
        if self.ppu_lower is not None:
            ds["95PPU_lower"] = (("observation", self.dim_names[list(self.dim_names.keys())[0]]), self.ppu_lower)
        if self.ppu_upper is not None:
            ds["95PPU_upper"] = (("observation", self.dim_names[list(self.dim_names.keys())[0]]), self.ppu_upper)

        coord_dict = {}
        for k,v in ds.dims.items():
            if k == 'objective_functions':
                coord_dict[k] = (k, objfunc_names)
            elif k == 'parameters':
                coord_dict[k] = (k, param_names)
            else:
                coord_dict[k] = (k, np.arange(v)+1)
            
        ds = ds.assign_coords(coord_dict)
        
        if self.thresholds is not None:
            obfthrs = np.empty(len(objfunc_names))
            for k,v in self.thresholds.items():
                if k == 'pfactor_threshold':
                    ds[k] = (('scalar',), np.array([v]))
                elif k == 'min_refined_params_threshold':
                    ds[k] = (('scalar',), np.array([v]))
                else:
                    if k in objfunc_names:
                        obidx = objfunc_names.index(k)
                        obfthrs[obidx] = v
            if not np.isinf(obfthrs).all():
                ds['obj_func_thresholds'] = (('objective_functions',), obfthrs)

        
        return ds


# TODO - This needs lots of improvements to generalize to iterative database writing (like for zarr)
# TODO - There also needs to be functionality for using an existing distribution's percentiles versus remaking the distribution based only on the bounds (traditional LHS)
def LHS_md(params: list[spotpy.parameter.Base], repetitions: int, dbase: MultiDimDb, use_distribution: bool = False):
    """

    Args:
        params:
        repetitions:
        dbase_name:
        dbase_format:

    """
    database = copy.deepcopy(dbase)
    param_dims = {}
    param_dim_names = {}
    for p in params:
        ndim = {p.name: p.dim}
        ndimname = {p.name: p.dim_name}
        param_dims.update(ndim)
        param_dim_names.update(ndimname)
    
    database.dims = param_dims
    database.dim_names = param_dim_names

    if use_distribution:
        Is = np.linspace(0, 1, repetitions + 1)
        Ie = np.roll(Is, -1)
        Is = Is[:-1].copy()
        Ie = Ie[:-1].copy()
        paramdict = {}
        for p in params:
            if p.rndfunctype == 'List':
                val_arr = p.values
                if len(val_arr.shape) != 2:
                    raise ValueError("For multidimensional LHS, a 2D paramter array is required for 'List' type.")
            else:
                vals = np.linspace(p.minbound, p.maxbound, repetitions)
                val_arr = np.repeat(vals[:,None], p.dim, axis=1)
            print(f"Sampling {repetitions} repetitions of the {p.name} parameter...")
            samples = []
            for i in tqdm.tqdm(range(len(Is)), desc=f'{p.name} samples', leave=False):
                rs_p = np.random.uniform(Is[i], Ie[i], p.dim)
                rs_v = np.nanquantile(val_arr, rs_p, axis=0)
                p_samps = rs_v[np.arange(p.dim), np.arange(p.dim)]
                samples.append(p_samps)

            paramdict.update({p.name: np.array(samples)})
    else:
        segment = 1 / float(repetitions)
        paramdict = {}
        for p in params:
            parmin = p.minbound
            parmax = p.maxbound
            
            if isinstance(parmin, float):
                parmin = np.repeat(parmin, p.dim)
            if isinstance(parmax, float):
                parmax = np.repeat(parmax, p.dim)
                
            matrix = np.empty((repetitions, p.dim))
            print(f"Sampling {repetitions} repetitions of the {p.name} parameter...")
            for i in tqdm.tqdm(range(repetitions), desc=f"{p.name} samples", leave=False):
                segmentMin = i * segment
                pointInSegment = segmentMin + (np.random.random() * segment)
                parset = pointInSegment * (parmax - parmin) + parmin
                matrix[i,:] = parset
            paramdict.update({p.name: matrix})
        
    # "Shuffle" or randomize the parameter sets (or combinations)
    for k,v in paramdict.items():
        np.random.shuffle(v)
        paramdict[k] = v
    
    database.save(param_dict=paramdict)
    
    if database.format == 'memory':
        if paramdict != database.parameter_samples:
            raise ValueError("The sampled parameter dictionary does not match the database parameter records...")
        else:
            paramdict = copy.deepcopy(database.parameter_samples)
        return paramdict, database
    else:    
        return paramdict


# function to build parameter list to be input into LHS function, include dimensions and dimension names as attributes of spotpy.parameter objects
def build_parameter_list(setup: MscuaSetup, parameter_dim: dict, parameter_dim_name: dict):
    
    cls = type(setup)
    class_vars = vars(cls).items()
    parameters = []
    for attrname, attrobj in class_vars:
        # Check if it is a spotpy parameter
        if isinstance(attrobj, spotpy.parameter.Base):
            if not attrobj.name:
                attrobj.name = attrname
            
            attrobj.dim = parameter_dim[attrobj.name]
            attrobj.dim_name = parameter_dim_name[attrobj.name]
            
            if attrobj.rndfunctype == 'List':
                if isinstance(attrobj.values, list):
                    attrobj.values = np.array(attrobj.values)
                if len(attrobj.values.shape) == 1:
                    if attrobj.values.shape[0] != parameter_dim[attrobj.name]:
                        raise ValueError("The provided parameter dimensions do not match the length of the List Parameter values.")
                    attrobj.maxbound = np.nanmax(attrobj.values)
                    attrobj.minbound = np.nanmin(attrobj.values)
                elif len(attrobj.values.shape) == 2:
                    if attrobj.values.shape[1] != parameter_dim[attrobj.name]:
                        raise ValueError("The provided parameter dimensions do not match the length of the List Parameter values.")
                    attrobj.maxbound = np.nanmax(attrobj.values, axis=0)
                    attrobj.minbound = np.nanmin(attrobj.values, axis=0)
                else:
                    raise NotImplementedError("List Parameter type with > 2 dimensions is not supported.")

            # Add parameter
            parameters.append(attrobj)

    return parameters


def query_parameters(params: Union[dict, MultiDimDb], rep_id: int):
    
    if rep_id == 0:
        raise IndexError("The rep_id argument is not zero based, for the first sample use rep_id=1")
    idx = rep_id - 1
    
    if isinstance(params, dict):
        q_par = {}
        for k,v in params.items():
            try:
                q = {k: v[idx,:]}
            except IndexError:
                print(f"rep_id = {rep_id}, there are only {v.shape[0]} parameters samples to query")
            q_par.update(q)
    elif isinstance(params, MultiDimDb):
        if params.format == 'memory':
            q_par = {}
            for k,v in params.parameter_records.items():
                try:
                    q = {k: v[idx,:]}
                except IndexError:
                    print(f"rep_id = {rep_id}, there are only {v.shape[0]} parameters samples to query")
                q_par.update(q)
        else:
            # need to query xarray dataset here and return a dict
            q_par = {}
    
    return q_par


def run_multidim_model_reps(setup: MscuaSetup, dbase: MultiDimDb):
    if dbase.format == 'memory':
        if not dbase.parameter_samples:
            raise AttributeError("No paramter samples have been saved to the input database.")
        
        itst = list(dbase.parameter_samples.keys())[0]
        reps = dbase.parameter_samples[itst].shape[0]
        print(f"Running model for {reps} repetitions in database...")
        for i in tqdm.tqdm(np.arange(reps) + 1, desc='simulation', leave=False):
            qps = query_parameters(dbase.parameter_samples, i)
            mod = setup.simulation(qps)
            dbase.save(simulations=mod)

## Setting up example

In [5]:
# load and clean field data
field = pd.read_csv(os.path.join(main_level, '1_Input', 'FieldData', 'F128_AggregatedDaily.csv'))
field["Date"] = pd.to_datetime(field["Date"])
field = field.loc[:, ["Date", "VWC_36in"]]
field

          Date  VWC_36in
0   2024-04-21  0.271221
1   2024-04-22  0.271664
2   2024-04-23  0.271748
3   2024-04-24  0.271658
4   2024-04-25  0.271545
..         ...       ...
163 2024-10-01  0.236960
164 2024-10-02  0.237193
165 2024-10-03  0.237371
166 2024-10-04  0.237555
167 2024-10-05  0.237709

[168 rows x 2 columns]

In [6]:
# filter sensor data to be same dates as weather data (which dictates hydrus output period)
field = field[field.Date.isin(pd.read_csv(os.path.join(main_level, '1_Input', 'WeatherData.csv')).Date)]
field

C:\Users\x63d979\AppData\Local\Temp\ipykernel_30936\1608174289.py:2: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  field = field[field.Date.isin(pd.read_csv(os.path.join(main_level, '1_Input', 'WeatherData.csv')).Date)]

          Date  VWC_36in
0   2024-04-21  0.271221
1   2024-04-22  0.271664
2   2024-04-23  0.271748
3   2024-04-24  0.271658
4   2024-04-25  0.271545
..         ...       ...
163 2024-10-01  0.236960
164 2024-10-02  0.237193
165 2024-10-03  0.237371
166 2024-10-04  0.237555
167 2024-10-05  0.237709

[168 rows x 2 columns]

### Test run_dual_perm()

In [7]:
#Running model with default Van Genuchten parameters
vgs = pd.read_csv(os.path.join(main_level, '1_Input', 'VGParamsDP.csv')).iloc[:, 2:]
alldata, hydrus_output = rh.run_dual_perm(vgs, field) # works and takes ~0.8 seconds to run

c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\run_hydrus.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.03556' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  allatm.loc[i, 'PotenitalEvap'] = allatm.loc[i,'ET_cm']
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\run_hydrus.py:44: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.254' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  allatm.loc[i,'PotentialTransp'] = allatm.loc[i, 'ET_cm']
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     2.1611 1.6612 1.9705 0.     3.3071
 0.     3.302  0.     2.4773 0.     0.     0.     0.     0.     0.
 0.     0.     0.     1.3602 1.27   1.27   1.27   1.2802 2.54   0.
 1.27   0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     1.524  1.524
 1.524  1.6498 1.5852 3.5933 0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     1.397  0.
 2.8059 0.     2.9623 0.     2.794  0.     2.794  1.4413 0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.    ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.      0.03556 0.10668 0.0762  0.03302 0.04826 0.127   0.18542 0.1778
 0.09652 0.04572 0.19304 0.23114 0.17272 0.03302 0.02032 0.04318 0.16002
 0.10668 0.127   0.18288 0.07874 0.0889  0.08382 0.06096 0.1524  0.04572
 0.03429 0.02286 0.05588 0.10414 0.11176 0.14478 0.26162 0.19304 0.20066
 0.1524  0.21336 0.10414 0.23622 0.27178 0.1778  0.3175  0.23622 0.06604
 0.13208 0.28702 0.2413  0.14478 0.1651  0.0762  0.06604 0.02286 0.01778
 0.05588 0.18542 0.20066 0.14732 0.05588 0.12446 0.21844 0.15494 0.17526
 0.03556 0.0508  0.06096 0.04318 0.0635  0.02794 0.0508  0.06604 0.17272
 0.22098 0.09398 0.10922 0.13208 0.19304 0.15494 0.08636 0.12954 0.1397
 0.2032  0.15494 0.11176 0.10922 0.17018 0.12192 0.12192 0.08128 0.19558
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.02286 0.21844 0.13462 0.1905  0.11938 0.19558
 0.18796 0.23368 0.2413  0.21082 0.15494 0.02032 0.07366 0.13716 0.1778
 0.18288 0.24892 0.36322 0.42164 0.26924 0.10922 0.06858 0.03302 0.02286
 0.02794 0.0254  0.02286 0.04064 0.06604 0.1016  0.13462 0.15748 0.11176
 0.14478 0.1905  0.23876 0.1143  0.2032  0.12954 0.12446 0.15494 0.28956
 0.13462 0.24892 0.18542 0.18796 0.09906 0.27432 0.19304 0.18796 0.1651
 0.33274 0.1524  0.01016 0.01778 0.06096 0.05842 0.18288 0.28194 0.10668
 0.0254  0.1143  0.1651  0.17018 0.16256 0.33782 0.25146 0.09144 0.03302
 0.1397  0.21082 0.04572 0.04064 0.13716 0.11684 0.10668 0.3302  0.06604
 0.2286  0.19304 0.20574 0.1651  0.2032  0.07366 0.0762  0.12954 0.1651
 0.09144 0.1905  0.07874 0.03302 0.10668 0.127   0.11684 0.04064 0.11176
 0.09144 0.1524  0.02794 0.08382 0.1905  0.0381  0.01524 0.00508 0.00762
 0.00508 0.02032 0.07874 0.01778 0.01651 0.01524 0.1143  0.12954 0.0381
 0.15494 0.14732 0.1651  0.19304 0.20574 0.26162 0.22352 0.24892 0.2413
 0.19558 0.08128 0.03048 0.0381  0.04572 0.02794 0.03302 0.0381  0.0381
 0.06858 0.0762  0.07112 0.03556 0.03175 0.02794 0.03302 0.0889  0.1524
 0.1016  0.17526 0.13462 0.127   0.20066 0.17018 0.26162 0.09398 0.0508
 0.22352 0.3302  0.19558 0.04064 0.04318 0.05334 0.09144 0.0762  0.11684
 0.3175  0.41656 0.31242 0.2159  0.23876 0.13716 0.13716 0.22098 0.1651
 0.18288 0.2921  0.22098 0.06604 0.1143  0.06858 0.0381  0.07874 0.11938
 0.1397  0.24638 0.13208 0.09398 0.1143  0.04064 0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.54102 0.19304 0.17526 0.46228 0.254   0.22352 0.33528 0.35306 0.2794
 0.17526 0.12954 0.14732 0.15494 0.3048  0.23368 0.25908 0.13716 0.25654
 0.48768 0.4064  0.20066 0.17272 0.254   0.1651  0.10668 0.27686 0.32766
 0.21336 0.08128 0.17526 0.14732 0.17018 0.21082 0.1016  0.21844 0.07874
 0.1524  0.28702 0.25146 0.11176 0.10414 0.18542 0.18288 0.2794  0.2413
 0.06858 0.14986 0.3175  0.13462 0.04064 0.03048 0.04064 0.0127  0.02032
 0.01778 0.01778 0.0762  0.02286 0.04064 0.01778 0.11938 0.03302 0.08128
 0.15748 0.04826 0.18034 0.28956 0.36576 0.12954 0.05842 0.06858 0.10668
 0.05588 0.13462 0.18542 0.10922 0.05842 0.02032 0.17272 0.12192 0.21844
 0.25146 0.17272 0.19812 0.18796 0.2032  0.21844 0.17526 0.20574 0.07874
 0.01524 0.      0.0127  0.0127  0.0127  0.01016 0.00508 0.01524 0.07112
 0.10668 0.06604 0.1905  0.04572 0.02286 0.05588 0.10668 0.127   0.20574
 0.04064 0.02032 0.01778 0.05588 0.14986 0.04572 0.15494 0.02794 0.03302]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.254   0.23114 0.10922 0.06604 0.16256 0.33274 0.37338 0.37846 0.4572
 0.54864 0.47244 0.18288 0.09652 0.18034 0.2921  0.4064  0.35052 0.12446
 0.12446 0.13716 0.1143  0.2159  0.25908 0.28194 0.36068 0.3683  0.23622
 0.37846 0.36322 0.41148 0.39624 0.35306 0.36322 0.39878 0.23876 0.09398
 0.28956 0.37084 0.27432 0.32512 0.2286  0.29972 0.18288 0.21336 0.42926
 0.51816 0.18542 0.33528 0.42672 0.4064  0.4445  0.35052 0.40894 0.2794
 0.14732 0.11938 0.10922 0.37846 0.44196 0.44958 0.33528 0.26162 0.10414
 0.1905  0.41656 0.37592 0.32258 0.4191  0.28448 0.19304 0.24638 0.41148
 0.41402 0.46482 0.44958 0.26924 0.4318  0.3937  0.34036 0.4699  0.4445
 0.34798 0.4064  0.32004 0.40132 0.34036 0.43942 0.34036 0.35052 0.4699
 0.46482 0.58928 0.44958 0.37592 0.29972 0.3937  0.3937  0.41148 0.42672
 0.46482 0.4191  0.3302  0.43434 0.3937  0.35306 0.41402 0.4318  0.46736
 0.4445  0.4191  0.43942 0.47244 0.46736 0.45974 0.4699  0.46482 0.44958
 0.34036 0.36068 0.3937  0.39116 0.41402 0.43942 0.43688 0.39624 0.35814
 0.19558 0.14986 0.34036 0.3556  0.4064  0.46228 0.39878 0.26924 0.3556
 0.41148 0.43688 0.32258 0.44958 0.55372 0.29972 0.25146 0.11938 0.36068
 0.40386 0.36322 0.28194 0.3683  0.32004 0.29972 0.37846 0.46482 0.37592
 0.28194 0.42926 0.37084 0.17272 0.27432 0.3429  0.26924 0.254   0.21336
 0.23622 0.25146 0.2921  0.24638 0.21844 0.2921  0.32258 0.46228 0.37592
 0.20066 0.18288 0.04826 0.04572 0.23622 0.2286  0.22606 0.28956 0.22098
 0.28702 0.23114 0.06604 0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.24892 0.38354 0.33274
 0.05334 0.04064 0.05334 0.09906 0.25654 0.36322 0.2286  0.30734 0.3048
 0.381   0.30988 0.2921  0.26162 0.11938 0.1397  0.10414 0.23622 0.43434
 0.35052 0.32512 0.44704 0.27432 0.254   0.12954 0.35306 0.32004 0.29464
 0.19558 0.13208 0.19558 0.32766 0.22606 0.30226 0.12954 0.04572 0.2667
 0.39878 0.42926 0.42418 0.381   0.21844 0.35814 0.48006 0.36068 0.35306
 0.24892 0.29718 0.28956 0.23368 0.25654 0.39878 0.31496 0.42164 0.41148
 0.4699  0.41148 0.36576 0.40132 0.3683  0.41148 0.46482 0.47752 0.4445
 0.44196 0.42672 0.41656 0.39878 0.45974 0.55118 0.5207  0.45466 0.41656
 0.32766 0.4318  0.09652 0.23368 0.37592 0.4191  0.33528 0.42672 0.55626
 0.49022 0.41148 0.44196 0.32258 0.21844 0.37592 0.26924 0.37084 0.42672
 0.24638 0.35814 0.37592 0.34798 0.4445  0.46228 0.4572  0.47752 0.4318
 0.43688 0.44958 0.42672 0.4826  0.46228 0.45212 0.37592 0.40894 0.41402
 0.37084 0.38608 0.4826  0.55626 0.58928 0.47244 0.4064  0.3429  0.44196
 0.381   0.4699  0.41402 0.42926 0.36322 0.13208 0.33274 0.34544 0.11938
 0.25146 0.31242 0.31496 0.36576 0.37846 0.32512 0.32258 0.40386 0.381
 0.35814 0.37592 0.43434 0.3429  0.28956 0.31496 0.37846 0.3429  0.37084
 0.34798 0.46228 0.26416 0.39624 0.36576 0.3048  0.28956 0.30226 0.29718
 0.29464 0.28956 0.30226 0.2921  0.28448 0.39624 0.18288 0.1524  0.0635
 0.23876 0.35814 0.17272 0.19812 0.16764 0.0889  0.24384 0.34544 0.19558
 0.32258 0.2667  0.44196 0.39624 0.3175  0.40894 0.23368 0.3175  0.20828
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.     ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)

run complete

c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:198: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = read_csv(file, skiprows=s, nrows=e - s - 2, usecols=usecols,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:203: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data = data.drop(index=data.index[0]).apply(to_numeric,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:198: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = read_csv(file, skiprows=s, nrows=e - s - 2, usecols=usecols,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:203: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data = data.drop(index=data.index[0]).apply(to_numeric,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:243: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df1 = read_csv(path, skiprows=start, index_col=0, nrows=end - start - 1,

In [ ]:
start = time.time()
alldata, hydrus_output = rh.run_dual_perm(vgs, field)

if time.time() - start > 5:  # suspicious
    alldata, hydrus_output = rh.run_with_timeout(
        vgs, field, fallback_shape=..., timeout=60
    )

c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\run_hydrus.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.03556' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  allatm.loc[i, 'PotenitalEvap'] = allatm.loc[i,'ET_cm']
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\run_hydrus.py:44: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.254' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  allatm.loc[i,'PotentialTransp'] = allatm.loc[i, 'ET_cm']
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     2.1611 1.6612 1.9705 0.     3.3071
 0.     3.302  0.     2.4773 0.     0.     0.     0.     0.     0.
 0.     0.     0.     1.3602 1.27   1.27   1.27   1.2802 2.54   0.
 1.27   0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     1.524  1.524
 1.524  1.6498 1.5852 3.5933 0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     1.397  0.
 2.8059 0.     2.9623 0.     2.794  0.     2.794  1.4413 0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.    ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.      0.03556 0.10668 0.0762  0.03302 0.04826 0.127   0.18542 0.1778
 0.09652 0.04572 0.19304 0.23114 0.17272 0.03302 0.02032 0.04318 0.16002
 0.10668 0.127   0.18288 0.07874 0.0889  0.08382 0.06096 0.1524  0.04572
 0.03429 0.02286 0.05588 0.10414 0.11176 0.14478 0.26162 0.19304 0.20066
 0.1524  0.21336 0.10414 0.23622 0.27178 0.1778  0.3175  0.23622 0.06604
 0.13208 0.28702 0.2413  0.14478 0.1651  0.0762  0.06604 0.02286 0.01778
 0.05588 0.18542 0.20066 0.14732 0.05588 0.12446 0.21844 0.15494 0.17526
 0.03556 0.0508  0.06096 0.04318 0.0635  0.02794 0.0508  0.06604 0.17272
 0.22098 0.09398 0.10922 0.13208 0.19304 0.15494 0.08636 0.12954 0.1397
 0.2032  0.15494 0.11176 0.10922 0.17018 0.12192 0.12192 0.08128 0.19558
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.02286 0.21844 0.13462 0.1905  0.11938 0.19558
 0.18796 0.23368 0.2413  0.21082 0.15494 0.02032 0.07366 0.13716 0.1778
 0.18288 0.24892 0.36322 0.42164 0.26924 0.10922 0.06858 0.03302 0.02286
 0.02794 0.0254  0.02286 0.04064 0.06604 0.1016  0.13462 0.15748 0.11176
 0.14478 0.1905  0.23876 0.1143  0.2032  0.12954 0.12446 0.15494 0.28956
 0.13462 0.24892 0.18542 0.18796 0.09906 0.27432 0.19304 0.18796 0.1651
 0.33274 0.1524  0.01016 0.01778 0.06096 0.05842 0.18288 0.28194 0.10668
 0.0254  0.1143  0.1651  0.17018 0.16256 0.33782 0.25146 0.09144 0.03302
 0.1397  0.21082 0.04572 0.04064 0.13716 0.11684 0.10668 0.3302  0.06604
 0.2286  0.19304 0.20574 0.1651  0.2032  0.07366 0.0762  0.12954 0.1651
 0.09144 0.1905  0.07874 0.03302 0.10668 0.127   0.11684 0.04064 0.11176
 0.09144 0.1524  0.02794 0.08382 0.1905  0.0381  0.01524 0.00508 0.00762
 0.00508 0.02032 0.07874 0.01778 0.01651 0.01524 0.1143  0.12954 0.0381
 0.15494 0.14732 0.1651  0.19304 0.20574 0.26162 0.22352 0.24892 0.2413
 0.19558 0.08128 0.03048 0.0381  0.04572 0.02794 0.03302 0.0381  0.0381
 0.06858 0.0762  0.07112 0.03556 0.03175 0.02794 0.03302 0.0889  0.1524
 0.1016  0.17526 0.13462 0.127   0.20066 0.17018 0.26162 0.09398 0.0508
 0.22352 0.3302  0.19558 0.04064 0.04318 0.05334 0.09144 0.0762  0.11684
 0.3175  0.41656 0.31242 0.2159  0.23876 0.13716 0.13716 0.22098 0.1651
 0.18288 0.2921  0.22098 0.06604 0.1143  0.06858 0.0381  0.07874 0.11938
 0.1397  0.24638 0.13208 0.09398 0.1143  0.04064 0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.54102 0.19304 0.17526 0.46228 0.254   0.22352 0.33528 0.35306 0.2794
 0.17526 0.12954 0.14732 0.15494 0.3048  0.23368 0.25908 0.13716 0.25654
 0.48768 0.4064  0.20066 0.17272 0.254   0.1651  0.10668 0.27686 0.32766
 0.21336 0.08128 0.17526 0.14732 0.17018 0.21082 0.1016  0.21844 0.07874
 0.1524  0.28702 0.25146 0.11176 0.10414 0.18542 0.18288 0.2794  0.2413
 0.06858 0.14986 0.3175  0.13462 0.04064 0.03048 0.04064 0.0127  0.02032
 0.01778 0.01778 0.0762  0.02286 0.04064 0.01778 0.11938 0.03302 0.08128
 0.15748 0.04826 0.18034 0.28956 0.36576 0.12954 0.05842 0.06858 0.10668
 0.05588 0.13462 0.18542 0.10922 0.05842 0.02032 0.17272 0.12192 0.21844
 0.25146 0.17272 0.19812 0.18796 0.2032  0.21844 0.17526 0.20574 0.07874
 0.01524 0.      0.0127  0.0127  0.0127  0.01016 0.00508 0.01524 0.07112
 0.10668 0.06604 0.1905  0.04572 0.02286 0.05588 0.10668 0.127   0.20574
 0.04064 0.02032 0.01778 0.05588 0.14986 0.04572 0.15494 0.02794 0.03302]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.254   0.23114 0.10922 0.06604 0.16256 0.33274 0.37338 0.37846 0.4572
 0.54864 0.47244 0.18288 0.09652 0.18034 0.2921  0.4064  0.35052 0.12446
 0.12446 0.13716 0.1143  0.2159  0.25908 0.28194 0.36068 0.3683  0.23622
 0.37846 0.36322 0.41148 0.39624 0.35306 0.36322 0.39878 0.23876 0.09398
 0.28956 0.37084 0.27432 0.32512 0.2286  0.29972 0.18288 0.21336 0.42926
 0.51816 0.18542 0.33528 0.42672 0.4064  0.4445  0.35052 0.40894 0.2794
 0.14732 0.11938 0.10922 0.37846 0.44196 0.44958 0.33528 0.26162 0.10414
 0.1905  0.41656 0.37592 0.32258 0.4191  0.28448 0.19304 0.24638 0.41148
 0.41402 0.46482 0.44958 0.26924 0.4318  0.3937  0.34036 0.4699  0.4445
 0.34798 0.4064  0.32004 0.40132 0.34036 0.43942 0.34036 0.35052 0.4699
 0.46482 0.58928 0.44958 0.37592 0.29972 0.3937  0.3937  0.41148 0.42672
 0.46482 0.4191  0.3302  0.43434 0.3937  0.35306 0.41402 0.4318  0.46736
 0.4445  0.4191  0.43942 0.47244 0.46736 0.45974 0.4699  0.46482 0.44958
 0.34036 0.36068 0.3937  0.39116 0.41402 0.43942 0.43688 0.39624 0.35814
 0.19558 0.14986 0.34036 0.3556  0.4064  0.46228 0.39878 0.26924 0.3556
 0.41148 0.43688 0.32258 0.44958 0.55372 0.29972 0.25146 0.11938 0.36068
 0.40386 0.36322 0.28194 0.3683  0.32004 0.29972 0.37846 0.46482 0.37592
 0.28194 0.42926 0.37084 0.17272 0.27432 0.3429  0.26924 0.254   0.21336
 0.23622 0.25146 0.2921  0.24638 0.21844 0.2921  0.32258 0.46228 0.37592
 0.20066 0.18288 0.04826 0.04572 0.23622 0.2286  0.22606 0.28956 0.22098
 0.28702 0.23114 0.06604 0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.24892 0.38354 0.33274
 0.05334 0.04064 0.05334 0.09906 0.25654 0.36322 0.2286  0.30734 0.3048
 0.381   0.30988 0.2921  0.26162 0.11938 0.1397  0.10414 0.23622 0.43434
 0.35052 0.32512 0.44704 0.27432 0.254   0.12954 0.35306 0.32004 0.29464
 0.19558 0.13208 0.19558 0.32766 0.22606 0.30226 0.12954 0.04572 0.2667
 0.39878 0.42926 0.42418 0.381   0.21844 0.35814 0.48006 0.36068 0.35306
 0.24892 0.29718 0.28956 0.23368 0.25654 0.39878 0.31496 0.42164 0.41148
 0.4699  0.41148 0.36576 0.40132 0.3683  0.41148 0.46482 0.47752 0.4445
 0.44196 0.42672 0.41656 0.39878 0.45974 0.55118 0.5207  0.45466 0.41656
 0.32766 0.4318  0.09652 0.23368 0.37592 0.4191  0.33528 0.42672 0.55626
 0.49022 0.41148 0.44196 0.32258 0.21844 0.37592 0.26924 0.37084 0.42672
 0.24638 0.35814 0.37592 0.34798 0.4445  0.46228 0.4572  0.47752 0.4318
 0.43688 0.44958 0.42672 0.4826  0.46228 0.45212 0.37592 0.40894 0.41402
 0.37084 0.38608 0.4826  0.55626 0.58928 0.47244 0.4064  0.3429  0.44196
 0.381   0.4699  0.41402 0.42926 0.36322 0.13208 0.33274 0.34544 0.11938
 0.25146 0.31242 0.31496 0.36576 0.37846 0.32512 0.32258 0.40386 0.381
 0.35814 0.37592 0.43434 0.3429  0.28956 0.31496 0.37846 0.3429  0.37084
 0.34798 0.46228 0.26416 0.39624 0.36576 0.3048  0.28956 0.30226 0.29718
 0.29464 0.28956 0.30226 0.2921  0.28448 0.39624 0.18288 0.1524  0.0635
 0.23876 0.35814 0.17272 0.19812 0.16764 0.0889  0.24384 0.34544 0.19558
 0.32258 0.2667  0.44196 0.39624 0.3175  0.40894 0.23368 0.3175  0.20828
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.     ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)

run complete

c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:198: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = read_csv(file, skiprows=s, nrows=e - s - 2, usecols=usecols,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:203: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data = data.drop(index=data.index[0]).apply(to_numeric,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:198: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = read_csv(file, skiprows=s, nrows=e - s - 2, usecols=usecols,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:203: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data = data.drop(index=data.index[0]).apply(to_numeric,
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\ReadFunctions.py:243: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df1 = read_csv(path, skiprows=start, index_col=0, nrows=end - start - 1,

In [ ]:
#Running model with diverging Van Genuchten parameters
vgs1 = [[0.05497188449858893, 0.44158225350339564, 0.025212344122472873, 1.5651329197092732, 271.1637047194382, 0.5, 0.03168699246402308, 0.5301523664001243, 0.5442781530609785, 2.26681537230208, 924.8945956319769, 0.5, 0.014270554638862298, 17.437027260820653, 0.4, 7.957333477415174, 4.262251754690671]]
alldata1, hydrus_output1 = rh.run_dual_perm(vgs1, field)

if time.time() - start > 5:  # suspicious
    alldata1, hydrus_output1 = rh.run_with_timeout(
        vgs1, field, fallback_shape=..., timeout=60
    )

c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\run_hydrus.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.03556' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  allatm.loc[i, 'PotenitalEvap'] = allatm.loc[i,'ET_cm']
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\run_hydrus.py:44: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.254' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  allatm.loc[i,'PotentialTransp'] = allatm.loc[i, 'ET_cm']
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     2.1611 1.6612 1.9705 0.     3.3071
 0.     3.302  0.     2.4773 0.     0.     0.     0.     0.     0.
 0.     0.     0.     1.3602 1.27   1.27   1.27   1.2802 2.54   0.
 1.27   0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     1.524  1.524
 1.524  1.6498 1.5852 3.5933 0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     1.397  0.
 2.8059 0.     2.9623 0.     2.794  0.     2.794  1.4413 0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.    ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.      0.03556 0.10668 0.0762  0.03302 0.04826 0.127   0.18542 0.1778
 0.09652 0.04572 0.19304 0.23114 0.17272 0.03302 0.02032 0.04318 0.16002
 0.10668 0.127   0.18288 0.07874 0.0889  0.08382 0.06096 0.1524  0.04572
 0.03429 0.02286 0.05588 0.10414 0.11176 0.14478 0.26162 0.19304 0.20066
 0.1524  0.21336 0.10414 0.23622 0.27178 0.1778  0.3175  0.23622 0.06604
 0.13208 0.28702 0.2413  0.14478 0.1651  0.0762  0.06604 0.02286 0.01778
 0.05588 0.18542 0.20066 0.14732 0.05588 0.12446 0.21844 0.15494 0.17526
 0.03556 0.0508  0.06096 0.04318 0.0635  0.02794 0.0508  0.06604 0.17272
 0.22098 0.09398 0.10922 0.13208 0.19304 0.15494 0.08636 0.12954 0.1397
 0.2032  0.15494 0.11176 0.10922 0.17018 0.12192 0.12192 0.08128 0.19558
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.02286 0.21844 0.13462 0.1905  0.11938 0.19558
 0.18796 0.23368 0.2413  0.21082 0.15494 0.02032 0.07366 0.13716 0.1778
 0.18288 0.24892 0.36322 0.42164 0.26924 0.10922 0.06858 0.03302 0.02286
 0.02794 0.0254  0.02286 0.04064 0.06604 0.1016  0.13462 0.15748 0.11176
 0.14478 0.1905  0.23876 0.1143  0.2032  0.12954 0.12446 0.15494 0.28956
 0.13462 0.24892 0.18542 0.18796 0.09906 0.27432 0.19304 0.18796 0.1651
 0.33274 0.1524  0.01016 0.01778 0.06096 0.05842 0.18288 0.28194 0.10668
 0.0254  0.1143  0.1651  0.17018 0.16256 0.33782 0.25146 0.09144 0.03302
 0.1397  0.21082 0.04572 0.04064 0.13716 0.11684 0.10668 0.3302  0.06604
 0.2286  0.19304 0.20574 0.1651  0.2032  0.07366 0.0762  0.12954 0.1651
 0.09144 0.1905  0.07874 0.03302 0.10668 0.127   0.11684 0.04064 0.11176
 0.09144 0.1524  0.02794 0.08382 0.1905  0.0381  0.01524 0.00508 0.00762
 0.00508 0.02032 0.07874 0.01778 0.01651 0.01524 0.1143  0.12954 0.0381
 0.15494 0.14732 0.1651  0.19304 0.20574 0.26162 0.22352 0.24892 0.2413
 0.19558 0.08128 0.03048 0.0381  0.04572 0.02794 0.03302 0.0381  0.0381
 0.06858 0.0762  0.07112 0.03556 0.03175 0.02794 0.03302 0.0889  0.1524
 0.1016  0.17526 0.13462 0.127   0.20066 0.17018 0.26162 0.09398 0.0508
 0.22352 0.3302  0.19558 0.04064 0.04318 0.05334 0.09144 0.0762  0.11684
 0.3175  0.41656 0.31242 0.2159  0.23876 0.13716 0.13716 0.22098 0.1651
 0.18288 0.2921  0.22098 0.06604 0.1143  0.06858 0.0381  0.07874 0.11938
 0.1397  0.24638 0.13208 0.09398 0.1143  0.04064 0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.54102 0.19304 0.17526 0.46228 0.254   0.22352 0.33528 0.35306 0.2794
 0.17526 0.12954 0.14732 0.15494 0.3048  0.23368 0.25908 0.13716 0.25654
 0.48768 0.4064  0.20066 0.17272 0.254   0.1651  0.10668 0.27686 0.32766
 0.21336 0.08128 0.17526 0.14732 0.17018 0.21082 0.1016  0.21844 0.07874
 0.1524  0.28702 0.25146 0.11176 0.10414 0.18542 0.18288 0.2794  0.2413
 0.06858 0.14986 0.3175  0.13462 0.04064 0.03048 0.04064 0.0127  0.02032
 0.01778 0.01778 0.0762  0.02286 0.04064 0.01778 0.11938 0.03302 0.08128
 0.15748 0.04826 0.18034 0.28956 0.36576 0.12954 0.05842 0.06858 0.10668
 0.05588 0.13462 0.18542 0.10922 0.05842 0.02032 0.17272 0.12192 0.21844
 0.25146 0.17272 0.19812 0.18796 0.2032  0.21844 0.17526 0.20574 0.07874
 0.01524 0.      0.0127  0.0127  0.0127  0.01016 0.00508 0.01524 0.07112
 0.10668 0.06604 0.1905  0.04572 0.02286 0.05588 0.10668 0.127   0.20574
 0.04064 0.02032 0.01778 0.05588 0.14986 0.04572 0.15494 0.02794 0.03302]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)
c:\Users\x63d979\Documents\HydrusCoding\Hydrus\Fairfield_DualPerm\2_Code\EditedFunctions_260226_mr.py:504: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.254   0.23114 0.10922 0.06604 0.16256 0.33274 0.37338 0.37846 0.4572
 0.54864 0.47244 0.18288 0.09652 0.18034 0.2921  0.4064  0.35052 0.12446
 0.12446 0.13716 0.1143  0.2159  0.25908 0.28194 0.36068 0.3683  0.23622
 0.37846 0.36322 0.41148 0.39624 0.35306 0.36322 0.39878 0.23876 0.09398
 0.28956 0.37084 0.27432 0.32512 0.2286  0.29972 0.18288 0.21336 0.42926
 0.51816 0.18542 0.33528 0.42672 0.4064  0.4445  0.35052 0.40894 0.2794
 0.14732 0.11938 0.10922 0.37846 0.44196 0.44958 0.33528 0.26162 0.10414
 0.1905  0.41656 0.37592 0.32258 0.4191  0.28448 0.19304 0.24638 0.41148
 0.41402 0.46482 0.44958 0.26924 0.4318  0.3937  0.34036 0.4699  0.4445
 0.34798 0.4064  0.32004 0.40132 0.34036 0.43942 0.34036 0.35052 0.4699
 0.46482 0.58928 0.44958 0.37592 0.29972 0.3937  0.3937  0.41148 0.42672
 0.46482 0.4191  0.3302  0.43434 0.3937  0.35306 0.41402 0.4318  0.46736
 0.4445  0.4191  0.43942 0.47244 0.46736 0.45974 0.4699  0.46482 0.44958
 0.34036 0.36068 0.3937  0.39116 0.41402 0.43942 0.43688 0.39624 0.35814
 0.19558 0.14986 0.34036 0.3556  0.4064  0.46228 0.39878 0.26924 0.3556
 0.41148 0.43688 0.32258 0.44958 0.55372 0.29972 0.25146 0.11938 0.36068
 0.40386 0.36322 0.28194 0.3683  0.32004 0.29972 0.37846 0.46482 0.37592
 0.28194 0.42926 0.37084 0.17272 0.27432 0.3429  0.26924 0.254   0.21336
 0.23622 0.25146 0.2921  0.24638 0.21844 0.2921  0.32258 0.46228 0.37592
 0.20066 0.18288 0.04826 0.04572 0.23622 0.2286  0.22606 0.28956 0.22098
 0.28702 0.23114 0.06604 0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.24892 0.38354 0.33274
 0.05334 0.04064 0.05334 0.09906 0.25654 0.36322 0.2286  0.30734 0.3048
 0.381   0.30988 0.2921  0.26162 0.11938 0.1397  0.10414 0.23622 0.43434
 0.35052 0.32512 0.44704 0.27432 0.254   0.12954 0.35306 0.32004 0.29464
 0.19558 0.13208 0.19558 0.32766 0.22606 0.30226 0.12954 0.04572 0.2667
 0.39878 0.42926 0.42418 0.381   0.21844 0.35814 0.48006 0.36068 0.35306
 0.24892 0.29718 0.28956 0.23368 0.25654 0.39878 0.31496 0.42164 0.41148
 0.4699  0.41148 0.36576 0.40132 0.3683  0.41148 0.46482 0.47752 0.4445
 0.44196 0.42672 0.41656 0.39878 0.45974 0.55118 0.5207  0.45466 0.41656
 0.32766 0.4318  0.09652 0.23368 0.37592 0.4191  0.33528 0.42672 0.55626
 0.49022 0.41148 0.44196 0.32258 0.21844 0.37592 0.26924 0.37084 0.42672
 0.24638 0.35814 0.37592 0.34798 0.4445  0.46228 0.4572  0.47752 0.4318
 0.43688 0.44958 0.42672 0.4826  0.46228 0.45212 0.37592 0.40894 0.41402
 0.37084 0.38608 0.4826  0.55626 0.58928 0.47244 0.4064  0.3429  0.44196
 0.381   0.4699  0.41402 0.42926 0.36322 0.13208 0.33274 0.34544 0.11938
 0.25146 0.31242 0.31496 0.36576 0.37846 0.32512 0.32258 0.40386 0.381
 0.35814 0.37592 0.43434 0.3429  0.28956 0.31496 0.37846 0.3429  0.37084
 0.34798 0.46228 0.26416 0.39624 0.36576 0.3048  0.28956 0.30226 0.29718
 0.29464 0.28956 0.30226 0.2921  0.28448 0.39624 0.18288 0.1524  0.0635
 0.23876 0.35814 0.17272 0.19812 0.16764 0.0889  0.24384 0.34544 0.19558
 0.32258 0.2667  0.44196 0.39624 0.3175  0.40894 0.23368 0.3175  0.20828
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.
 0.      0.      0.      0.      0.      0.      0.      0.      0.     ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.atmosphere.update(atmosphere)

In [ ]:
def nse_md(observation: np.ndarray, simulation: np.ndarray, return_dict: bool = False, axis=0):
    if observation.shape[axis] == simulation.shape[axis]:
        mean_observed = np.nanmean(observation, axis=axis)
        # compute numerator and denominator
        numerator = np.nansum((observation - simulation) ** 2, axis=axis)
        denominator = np.nansum((observation - mean_observed) ** 2, axis=axis)
        # compute coefficient
        nse = 1 - (numerator / denominator)
        if return_dict:
            return {'nse': nse}
        else:
            return nse
    else:
        raise ValueError("evaluation and simulation data do not have the same length.")

In [ ]:
observation = np.array(field.drop(columns=["Date"]))
observation.shape

In [ ]:
# Calculate NSE for working example
nse_md(observation=observation, simulation=hydrus_output)

In [ ]:
# Calculate NSE for diverged example
nse_md(observation=observation, simulation=hydrus_output)

In [ ]:
# plot observed and simulated results at observation node

plt.figure()
plt.plot(field["Date"], field["VWC_36in"], label='Sensor Readings')
plt.plot(field["Date"], hydrus_output, label='Hydrus Simulation')
plt.xlabel("Date")
plt.ylabel("VWC (cm3/cm3)")
plt.title("Soil Moisture, 36in")
plt.xticks(rotation= 45)
plt.legend()
plt.show()

## Now back to Calibration!

### Sensitivity Analysis

In [ ]:
class MscuaSetupSA:
    # Define parameters here (before __init__) as variables
    # These are the parameters specific to your model and will need to be defined for each MscuaSetup class

    # Will need different variables for each layer, too (thetar_1, thetar_2, etc)
    
    # parse these within the run_hyrdus function, turn into df 
    thetar = spotpy.parameter.Uniform(low=0.05, high=0.1)
    thetas = spotpy.parameter.Uniform(low=0.35, high=0.5)
    alpha = spotpy.parameter.Uniform(low=0.005, high=0.04)
    n = spotpy.parameter.Uniform(low=1.1, high=2.0)
    ksat = spotpy.parameter.Uniform(low=5.0, high=500)
    l = spotpy.parameter.Uniform(low=0.5, high=0.5)
    thrfr = spotpy.parameter.Uniform(low=0, high=0.1)
    thsfr = spotpy.parameter.Uniform(low=0.2, high=0.8)
    alphafr = spotpy.parameter.Uniform(low=0.001, high=0.8)
    nfr = spotpy.parameter.Uniform(low=1.01, high=7)
    ksfr = spotpy.parameter.Uniform(low=1, high=1000)
    lfr = spotpy.parameter.Uniform(low=0.5, high=0.5)
    w = spotpy.parameter.Uniform(low=0.001, high=0.25)
    beta = spotpy.parameter.Uniform(low=1.0, high=20.0)
    gamma = spotpy.parameter.Uniform(low=0.4, high=0.4)
    a = spotpy.parameter.Uniform(low=0.1, high=10)
    ka = spotpy.parameter.Uniform(low=0.00001, high=10.0)

    def __init__(self, objective_funcs, dbase: Optional[Union[str, Path, MultiDimDb]] = None):
        # define the multidimensional parameter space here
        # use identical names as you did above for your spotpy parameter definitions (the variable assignment name)
        # if using spatial data this would be the number of features you are calibrating
        self.parameter_dimension = {
            "thetar": 1, 
            "thetas": 1, 
            "alpha": 1, 
            "n": 1, 
            "ksat": 1,
            "l": 1,
            "thrfr": 1,
            "thsfr": 1,
            "alphafr": 1,
            "nfr": 1,
            "ksfr": 1,
            "lfr": 1,
            "w": 1,
            "beta": 1,
            "gamma": 1,
            "a": 1,
            "ka": 1
        }
        # This customizes the dimension name that is carried through the database, here I used "curve" but this could be
        #   feature, model, field, HRU, whatever descriptive name the parameter is attached to.
        self.param_dim_names = {
            "thetar": 'field', 
            "thetas": 'field', 
            "alpha": 'field', 
            "n": 'field', 
            "ksat": 'field',
            "l": 'field',
            "thrfr": 'field',
            "thsfr": 'field',
            "alphafr": 'field',
            "nfr": 'field',
            "ksfr": 'field',
            "lfr": 'field',
            "w": 'field',
            "beta": 'field',
            "gamma": 'field',
            "a": 'field',
            "ka":'field' 
        }
        # These attributes may be specific to your model setup, in-data might be a file path to an input file for instance
        #   and observation data may come from another file.
        self.observation_data = np.array(field.drop(columns=["Date"]))

        # This can be left alone, this just ensures multiple objective functions can be passed during setup or treated as an iterable
        if isinstance(objective_funcs, list):
            self.objfuncs = objective_funcs
        else:
            self.objfuncs = [objective_funcs]
    
    # This method must be in the setup class, it is called during calibration to run the model, its only input should be a set
    #   of parameters. This could be an ordered list, tuple, however you want to set it up. I used a dictionary because it maintains
    #   reference to the parameter name and then you don't have to worry about order. This returns model output...for more complex model
    #   setups you might have a lot of code here to ingest parameters, change the parameters in the model files, and process the model outputs
    #   so that they can be returned as a Python object.
    def simulation(self, params):
        # may need to be changed so that I'm not passing random global variables.
        params_df = pd.DataFrame(params)
        params_array = [list(params_df.iloc[row, :]) for row in range(len(params_df))]
        print("params:", params_array)

        modout = rh.run_with_timeout(
            params_array,
            field,
            fallback_shape=np.array(field.drop(columns=["Date"])).shape,
            timeout=300     # 5 mins
        )
        return modout
    

    # This is a required method. It can be more complex if needed but it doesn't really need any arguments, it just needs to
    #   return the observation data to compare with the modeled data.
    def evaluation(self):
        return self.observation_data

    # This must return a dictionary where the keys are the objective function names
    # This is set up to calculate an entire 3D array of simulation results - dimensions (model reps, model vals, # models)
    # This can be customized to whatever you need for your model, the multidimensional objective functions included above can be manipulated by
    #   passing the axis argument (calculated objective function on a particular axis or for the entire array) they also include an option to return a
    #   dictionary with the objective function name (default is to just return numpy array), this dictionary is necessary for tracking results
    #   through the algorithm for each objective function.
    def objectivefunction(self, observation, simulation):
        results = {}
        for o in tqdm.tqdm(self.objfuncs, desc="Calculating Objective Functions", leave=False):
            r = o(observation=observation, simulation=simulation, return_dict=True)
            results.update(r)
        return results

In [ ]:
SAsetup = MscuaSetupSA([nse_md])

In [ ]:
sa = SensitivityAnalysis(SAsetup)

In [ ]:
sa.sample()

In [ ]:
sa.results

### Calibration Iteration 1

Now we define the Setup Class for the calibration algorithm. This is the key ingredient for the MSCUA multidimensional algorithm. The Setup Class is the custom class that links your model to the database, and the relevant algorithm methods. The structure can remain the same but most things will need to be tailored to your model.

In [ ]:
class MscuaSetupIter1:
    # Define parameters here (before __init__) as variables
    # These are the parameters specific to your model and will need to be defined for each MscuaSetup class

    # Will need different variables for each layer, too (thetar_1, thetar_2, etc)
    
    # parse these within the run_hyrdus function, turn into df 
    thetar = spotpy.parameter.Uniform(low=0.05, high=0.1)
    thetas = spotpy.parameter.Uniform(low=0.35, high=0.5)
    alpha = spotpy.parameter.Uniform(low=0.005, high=0.04)
    n = spotpy.parameter.Uniform(low=1.1, high=2.0)
    ksat = spotpy.parameter.Uniform(low=5.0, high=500)
    l = spotpy.parameter.Uniform(low=0.5, high=0.5)
    thrfr = spotpy.parameter.Uniform(low=0, high=0.1)
    thsfr = spotpy.parameter.Uniform(low=0.2, high=0.8)
    alphafr = spotpy.parameter.Uniform(low=0.001, high=0.8)
    nfr = spotpy.parameter.Uniform(low=1.01, high=7)
    ksfr = spotpy.parameter.Uniform(low=1, high=1000)
    lfr = spotpy.parameter.Uniform(low=0.5, high=0.5)
    w = spotpy.parameter.Uniform(low=0.001, high=0.25)
    beta = spotpy.parameter.Uniform(low=1.0, high=20.0)
    gamma = spotpy.parameter.Uniform(low=0.4, high=0.4)
    a = spotpy.parameter.Uniform(low=0.1, high=10)
    ka = spotpy.parameter.Uniform(low=0.00001, high=10.0)

    def __init__(self, objective_funcs, dbase: Optional[Union[str, Path, MultiDimDb]] = None):
        # define the multidimensional parameter space here
        # use identical names as you did above for your spotpy parameter definitions (the variable assignment name)
        # if using spatial data this would be the number of features you are calibrating
        self.parameter_dimension = {
            "thetar": 1, 
            "thetas": 1, 
            "alpha": 1, 
            "n": 1, 
            "ksat": 1,
            "l": 1,
            "thrfr": 1,
            "thsfr": 1,
            "alphafr": 1,
            "nfr": 1,
            "ksfr": 1,
            "lfr": 1,
            "w": 1,
            "beta": 1,
            "gamma": 1,
            "a": 1,
            "ka": 1
        }
        # This customizes the dimension name that is carried through the database, here I used "curve" but this could be
        #   feature, model, field, HRU, whatever descriptive name the parameter is attached to.
        self.param_dim_names = {
            "thetar": 'field', 
            "thetas": 'field', 
            "alpha": 'field', 
            "n": 'field', 
            "ksat": 'field',
            "l": 'field',
            "thrfr": 'field',
            "thsfr": 'field',
            "alphafr": 'field',
            "nfr": 'field',
            "ksfr": 'field',
            "lfr": 'field',
            "w": 'field',
            "beta": 'field',
            "gamma": 'field',
            "a": 'field',
            "ka":'field' 
        }
        # These attributes may be specific to your model setup, in-data might be a file path to an input file for instance
        #   and observation data may come from another file.
        self.observation_data = np.array(field.drop(columns=["Date"]))

        # This can be left alone, this just ensures multiple objective functions can be passed during setup or treated as an iterable
        if isinstance(objective_funcs, list):
            self.objfuncs = objective_funcs
        else:
            self.objfuncs = [objective_funcs]
    
    # This method must be in the setup class, it is called during calibration to run the model, its only input should be a set
    #   of parameters. This could be an ordered list, tuple, however you want to set it up. I used a dictionary because it maintains
    #   reference to the parameter name and then you don't have to worry about order. This returns model output...for more complex model
    #   setups you might have a lot of code here to ingest parameters, change the parameters in the model files, and process the model outputs
    #   so that they can be returned as a Python object.
    def simulation(self, params):
        # may need to be changed so that I'm not passing random global variables.
        params_df = pd.DataFrame(params)
        params_array = []
        for row in range(len(params_df)):
            df = params_df.iloc[row, : ]
            params_array.append(list(df))
        modout = run_dual_perm(vgs=params_array)[1]

        return modout
        
    # This is a required method. It can be more complex if needed but it doesn't really need any arguments, it just needs to
    #   return the observation data to compare with the modeled data.
    def evaluation(self):
        return self.observation_data

    # This must return a dictionary where the keys are the objective function names
    # This is set up to calculate an entire 3D array of simulation results - dimensions (model reps, model vals, # models)
    # This can be customized to whatever you need for your model, the multidimensional objective functions included above can be manipulated by
    #   passing the axis argument (calculated objective function on a particular axis or for the entire array) they also include an option to return a
    #   dictionary with the objective function name (default is to just return numpy array), this dictionary is necessary for tracking results
    #   through the algorithm for each objective function.
    def objectivefunction(self, observation, simulation):
        print(observation.shape, simulation.shape)
        results = {}
        for o in tqdm.tqdm(self.objfuncs, desc="Calculating Objective Functions", leave=False):
            r = o(observation=observation, simulation=simulation, return_dict=True, axis=1)
            results.update(r)
        
        return results

In [ ]:
# initialize the setup class with the normalized root mean square error objective function.
setup = MscuaSetupIter1([nse_md])

In [ ]:
# initialize a new MSCUA sample
sampler = MsCua(setup)

Now we will run the ```.sample()``` method which will sample the parameters space based on the reps argument, run the model, calculate objective function values, and filter parameter distributions based on the provided thresholds. The ```.sample()``` method will return index arrays if certain threshold requirements are not met. While most of the work writes directly to the database, I assign the output "results" variable to capture any failed iterations. This can be used later to filter those problem indexes out.

In [ ]:
results = sampler.sample(500, {'nse': -3.0}, use_distribution=False)